### ISSUE TITLE
SigSegv from log_expr_node_format_location()

### ISSUE THREAD

**Issue by mitzkia** [syslog-ng/syslog-ng#1986]
Reproduction:
1, Start syslog-ng in foreground with the given configuration: sbin/syslog-ng -Fedv --enable-core
2, send 100 messages to syslog-ng (which fills the buffer): `bin/loggen -U -SP -n 100 -I 1000 -i 127.0.0.1 9999`
3, send a reload to syslog-ng: `sbin/syslog-ng-ctl reload`
4, open destination side: `nc -lk 127.0.0.1 8888`
5, send a reload again: `sbin/syslog-ng-ctl reload`

syslog-ng config:
```
@version: 3.14
source s_syslog {
    syslog(port(9999) keep_alive(no)
            transport(tls)
            tls(
                peer-verify(optional-untrusted)
                ca-dir("path for cadir")
                key-file("path for key file")
                cert-file("path for cert file")
            )
    );
};

destination d_file {
    network("127.0.0.1" port(8888));
};

log {
    source(s_syslog);
    destination(d_file);
    flags(flow-control);
};
```
Crash can be reproduced also with:
 * if we replace syslog() driver with network() driver.

The crash can not reproduced if:
 * we not fill up the buffer, we must send at least 100 messages
 * we use tcp() driver with tls instead of syslog() driver with tls
 * we not using keep_alive(no) on source side
 * we not using tls in syslog() driver

syslog-ng was installed from source:
last commit id: 3fc6851448133cbf1571f0d07a434bf59cdd9756

bt
```
Thread 2 "syslog-ng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff566a700 (LWP 12523)]
0x00007ffff7238cc0 in _IO_vfprintf_internal (s=s@entry=0x7ffff56674a0, format=<optimized out>, format@entry=0x7ffff7b8cc87 "%s:%d:%d", 
    ap=ap@entry=0x7ffff5667610) at vfprintf.c:1632
1632	vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7238cc0 in _IO_vfprintf_internal (s=s@entry=0x7ffff56674a0, format=<optimized out>, 
    format@entry=0x7ffff7b8cc87 "%s:%d:%d", ap=ap@entry=0x7ffff5667610) at vfprintf.c:1632
#1  0x00007ffff7300896 in ___vsnprintf_chk (s=0x7ffff5667740 "", maxlen=<optimized out>, flags=1, slen=<optimized out>, 
    format=0x7ffff7b8cc87 "%s:%d:%d", args=0x7ffff5667610) at vsnprintf_chk.c:63
#2  0x00007ffff785ec5f in g_snprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7b19d21 in log_expr_node_format_location (self=0x65e130, buf=0x7ffff5667740 "", buf_len=128) at ../lib/cfg-tree.c:146
#4  0x00007ffff7b19d99 in log_expr_node_location_tag (self=0x65e130) at ../lib/cfg-tree.c:161
#5  0x00007ffff7b2460d in log_pipe_location_tag (pipe=0x63dc30) at ../lib/logpipe.c:33
#6  0x00007ffff7b28263 in log_source_wakeup (self=0x63dc30) at ../lib/logsource.c:44
#7  0x00007ffff7b282f4 in _flow_control_window_size_adjust (self=0x63dc30, window_size_increment=1) at ../lib/logsource.c:57
#8  0x00007ffff7b284f3 in log_source_flow_control_adjust (self=0x63dc30, window_size_increment=1) at ../lib/logsource.c:126
#9  0x00007ffff7b3d5cc in early_ack_tracker_manage_msg_ack (s=0x63df50, msg=0x7ffff00289a0, ack_type=AT_PROCESSED)
    at ../lib/early_ack_tracker.c:67
#10 0x00007ffff7b28217 in ack_tracker_manage_msg_ack (self=0x63df50, msg=0x7ffff00289a0, ack_type=AT_PROCESSED)
    at ../lib/ack_tracker.h:84
---Type <return> to continue, or q <return> to quit---
#11 0x00007ffff7b28536 in log_source_msg_ack (msg=0x7ffff00289a0, ack_type=AT_PROCESSED) at ../lib/logsource.c:140
#12 0x00007ffff7b7aa54 in log_msg_refcache_stop () at ../lib/logmsg/logmsg.c:1741
#13 0x00007ffff7b2dc43 in log_writer_write_message (self=0x645450, msg=0x7ffff00289a0, path_options=0x7ffff56679b0, 
    write_error=0x7ffff56679a0) at ../lib/logwriter.c:1146
#14 0x00007ffff7b2ddd8 in log_writer_flush (self=0x645450, flush_mode=LW_FLUSH_NORMAL) at ../lib/logwriter.c:1206
#15 0x00007ffff7b2baae in log_writer_work_perform (s=0x645450) at ../lib/logwriter.c:184
#16 0x00007ffff7b30eba in _work (self=0x645668) at ../lib/mainloop-io-worker.c:52
#17 0x00007ffff7b853e3 in iv_work_thread_got_event (_thr=0x63cb40) at ../../../../lib/ivykis/src/iv_work.c:106
#18 0x00007ffff7b83b65 in __iv_event_run_pending_events (_st=0x7ffff00008c0) at ../../../../lib/ivykis/src/iv_event.c:56
#19 0x00007ffff7b83c9c in iv_event_run_pending_events () at ../../../../lib/ivykis/src/iv_event.c:93
#20 0x00007ffff7b8a768 in iv_fd_epoll_timerfd_poll (st=0x7ffff00008c0, active=0x7ffff5667bc0, abs=0x63cb88)
    at ../../../../lib/ivykis/src/iv_fd_epoll.c:484
#21 0x00007ffff7b86865 in iv_fd_poll_and_run (st=0x7ffff00008c0, abs=0x63cb88) at ../../../../lib/ivykis/src/iv_fd.c:206
#22 0x00007ffff7b87cb4 in iv_main () at ../../../../lib/ivykis/src/iv_main_posix.c:112
#23 0x00007ffff7b8568f in iv_work_thread (_thr=0x63cb40) at ../../../../lib/ivykis/src/iv_work.c:185
#24 0x00007ffff7b88f2b in iv_thread_handler (_thr=0x63e1e0) at ../../../../lib/ivykis/src/iv_thread_posix.c:112
#25 0x00007ffff75bb6ba in start_thread (arg=0x7ffff566a700) at pthread_create.c:333
#26 0x00007ffff72f141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

bt full
```
Thread 3 "syslog-ng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff566a700 (LWP 12179)]
0x00007ffff7238cc0 in _IO_vfprintf_internal (s=s@entry=0x7ffff56674a0, format=<optimized out>, format@entry=0x7ffff7b8cc87 "%s:%d:%d", 
    ap=ap@entry=0x7ffff5667610) at vfprintf.c:1632
1632	vfprintf.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff7238cc0 in _IO_vfprintf_internal (s=s@entry=0x7ffff56674a0, format=<optimized out>, 
    format@entry=0x7ffff7b8cc87 "%s:%d:%d", ap=ap@entry=0x7ffff5667610) at vfprintf.c:1632
        len = <optimized out>
        string_malloced = 0
        step0_jumps = {0, -4693, -4638, 73, 167, -4969, 1011, 437, -998, -752, 776, -7971, -7884, -7787, -7688, -7641, -4462, -4863, 
          -1720, -2409, -1551, -30, -4147, -4051, -1688, -8907, -2093, -7690, -7787, 350}
        space = <optimized out>
        is_short = <optimized out>
        use_outdigits = <optimized out>
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, -752, 776, -7971, -7884, -7787, -7688, -7641, -4462, -4863, -1720, -2409, -1551, 
          -30, -4147, -4051, -1688, -8907, -2093, -7690, -7787, 0}
        group = <optimized out>
        prec = -1
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 776, -7971, -7884, -7787, -7688, -7641, -4462, -4863, -1720, -2409, -1551, -30, 
          -4147, -4051, -1688, -8907, -2093, -7690, -7787, 0}
---Type <return> to continue, or q <return> to quit---
        string = 0x31 <error: Cannot access memory at address 0x31>
        left = <optimized out>
        is_long_double = <optimized out>
        width = <optimized out>
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 863, 0, 0, 0, -7688, -7641, -4462, -4863, -1720, 0, 0, 0, 0, -4051, 0, 0, 0, 0, 
          0, 0}
        alt = <optimized out>
        showsign = <optimized out>
        is_long = 0
        is_char = <optimized out>
        pad = <optimized out>
        step3b_jumps = {0 <repeats 11 times>, -7884, 0, 0, -7688, -7641, -4462, -4863, -1720, -2409, -1551, -30, -4147, -4051, -1688, 
          -8907, -2093, 0, 0, 0}
        step4_jumps = {0 <repeats 14 times>, -7688, -7641, -4462, -4863, -1720, -2409, -1551, -30, -4147, -4051, -1688, -8907, -2093, 
          0, 0, 0}
        is_negative = <optimized out>
        number = <optimized out>
        base = <optimized out>
        the_arg = {pa_wchar = 0 L'\000', pa_int = 0, pa_long_int = 0, pa_long_long_int = 0, pa_u_int = 0, pa_u_long_int = 0, 
          pa_u_long_long_int = 0, pa_double = 0, pa_long_double = <invalid float value>, pa_string = 0x0, pa_wstring = 0x0, 
          pa_pointer = 0x0, pa_user = 0x0}
        spec = <optimized out>
        _buffer = {__routine = 0x7fff0000000a, __arg = 0x6, __canceltype = -177834750, __prev = 0x7}
        _avail = <optimized out>
        thousands_sep = 0x0
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        done = <optimized out>
        f = 0x7ffff7b8cc88 "s:%d:%d"
        lead_str_end = 0x7ffff7b8cc87 "%s:%d:%d"
        end_of_spec = <optimized out>
        work_buffer = "\342\371\270\367\377\177\000\000\000\000\000\000\001\000\000\000 qf\365\377\177\000\000\000\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\000\000\000\000\000\000\000\000\060qf\365\377\177\000\000\342\371\270\367\377\177\000\000\002\000\000\000\377\177\000\000\001\000\000\000\000\000\000\000guf\365\377\177\000\000\004\000\000\000\000\000\000\000z\235\235\366\377\177\000\000\000\000\000\000\001\000\000\000\200qf\365\377\177\000\000\030\000\000\000\060\000\000\000\240wf\365\377\177\000\000\340vf\365\377\177\000\000\200pd\000\000\000\000\000z\235\235\366\377\177\000\000\001\000\000\000\000\000\000\000\360pf\365\377\177\000\000\000{f\365\37---Type <return> to continue, or q <return> to quit---
7\177\000\000\000.\366鄍\253\060\200qf\365\377\177\000\000?ұ"...
        workstart = <optimized out>
        workend = <optimized out>
        ap_save = <error reading variable ap_save (Attempt to dereference a generic pointer.)>
        nspecs_done = 0
        save_errno = 0
        readonly_format = 0
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
#1  0x00007ffff7300896 in ___vsnprintf_chk (s=0x7ffff5667740 "", maxlen=<optimized out>, flags=1, slen=<optimized out>, 
    format=0x7ffff7b8cc87 "%s:%d:%d", args=0x7ffff5667610) at vsnprintf_chk.c:63
        sf = {f = {_sbf = {_f = {_flags = -72515583, _IO_read_ptr = 0x7ffff5667740 "", _IO_read_end = 0x7ffff5667740 "", 
                _IO_read_base = 0x7ffff5667740 "", _IO_write_base = 0x7ffff5667740 "", _IO_write_ptr = 0x7ffff5667740 "", 
                _IO_write_end = 0x7ffff56677bf "", _IO_buf_base = 0x7ffff5667740 "", _IO_buf_end = 0x7ffff56677bf "", 
                _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, _markers = 0x0, _chain = 0x0, _fileno = -177834672, 
                _flags2 = 4, _old_offset = 140737310520656, _cur_column = 0, _vtable_offset = 102 'f', 
                _shortbuf = <incomplete sequence \365>, _lock = 0x0, _offset = 140737310521024, _codecvt = 0x1, 
                _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x50444441fbad8001, __pad5 = 140737310521411, 
                _mode = -1, _unused2 = "\377\177\000\000Cxf\365\377\177\000\000Cxf\365\377\177\000"}, 
              vtable = 0x7ffff75ad4a0 <_IO_strn_jumps>}, _s = {_allocate_buffer = 0x0, _free_buffer = 0x7ffff5667843}}, 
          overflow_buf = "\257xf\365\377\177", '\000' <repeats 42 times>, "\361\211\231\n\004\000\000\000\017vf\365\377\177\000"}
        ret = <optimized out>
#2  0x00007ffff785ec5f in g_snprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff7b19d21 in log_expr_node_format_location (self=0x65b530, buf=0x7ffff5667740 "", buf_len=128) at ../lib/cfg-tree.c:146
        node = 0x65b530
#4  0x00007ffff7b19d99 in log_expr_node_location_tag (self=0x65b530) at ../lib/cfg-tree.c:161
        buf = "\000wf\365\377\177\000\000\355_\262\367\377\177\000\000 xf\365\001\000\000\000\320Yd\000\000\000\000\000\000{f\365\377\177\000\000\000\000\200\000\001\000\000\000\320Yd\000\000\000\000\000\b<\002\360\377\177\000\000\b<\002\360\377\177\000\000\200;\002\360\377\177\000\000\377\377\377\377", '\000' <repeats 12 times>, "\001\000\000\000\000\000\000\000\000.\366鄍\253\060\320wf\365\377\177\000\000\000\266\262\367\377\177\000"
#5  0x00007ffff7b2460d in log_pipe_location_tag (pipe=0x6395d0) at ../lib/logpipe.c:33
No locals.
#6  0x00007ffff7b28263 in log_source_wakeup (self=0x6395d0) at ../lib/logsource.c:44
No locals.
#7  0x00007ffff7b282f4 in _flow_control_window_size_adjust (self=0x6395d0, window_size_increment=1) at ../lib/logsource.c:57
---Type <return> to continue, or q <return> to quit---
        old_window_size = 0
#8  0x00007ffff7b284f3 in log_source_flow_control_adjust (self=0x6395d0, window_size_increment=1) at ../lib/logsource.c:126
No locals.
#9  0x00007ffff7b3d5cc in early_ack_tracker_manage_msg_ack (s=0x6593f0, msg=0x7ffff0023b80, ack_type=AT_PROCESSED)
    at ../lib/early_ack_tracker.c:67
        self = 0x6593f0
#10 0x00007ffff7b28217 in ack_tracker_manage_msg_ack (self=0x6593f0, msg=0x7ffff0023b80, ack_type=AT_PROCESSED)
    at ../lib/ack_tracker.h:84
No locals.
#11 0x00007ffff7b28536 in log_source_msg_ack (msg=0x7ffff0023b80, ack_type=AT_PROCESSED) at ../lib/logsource.c:140
        ack_tracker = 0x6593f0
#12 0x00007ffff7b7aa54 in log_msg_refcache_stop () at ../lib/logmsg/logmsg.c:1741
        ack_type_cumulated = AT_PROCESSED
        old_value = 32771
        current_cached_acks = -1
        current_cached_abort = 0
        current_cached_suspend = 0
        __func__ = "log_msg_refcache_stop"
#13 0x00007ffff7b2dc43 in log_writer_write_message (self=0x645450, msg=0x7ffff0023b80, path_options=0x7ffff56679b0, 
    write_error=0x7ffff56679a0) at ../lib/logwriter.c:1146
        consumed = 1
#14 0x00007ffff7b2ddd8 in log_writer_flush (self=0x645450, flush_mode=LW_FLUSH_NORMAL) at ../lib/logwriter.c:1206
        path_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x0}
        msg = 0x7ffff0023b80
        mark = 0
        write_error = 0
#15 0x00007ffff7b2baae in log_writer_work_perform (s=0x645450) at ../lib/logwriter.c:184
        self = 0x645450
        __func__ = "log_writer_work_perform"
#16 0x00007ffff7b30eba in _work (self=0x645668) at ../lib/mainloop-io-worker.c:52
No locals.
#17 0x00007ffff7b853e3 in iv_work_thread_got_event (_thr=0x63aab0) at ../../../../lib/ivykis/src/iv_work.c:106
        work = 0x645688
        thr = 0x63aab0
        pool = 0x636550
---Type <return> to continue, or q <return> to quit---
        last_seq = 27
#18 0x00007ffff7b83b65 in __iv_event_run_pending_events (_st=0x7ffff0024eb0) at ../../../../lib/ivykis/src/iv_event.c:56
        ie = 0x63aad0
        empty_now = 1
        st = 0x7ffff0024eb0
        events = {next = 0x7ffff5667ab0, prev = 0x7ffff5667ab0}
#19 0x00007ffff7b83c9c in iv_event_run_pending_events () at ../../../../lib/ivykis/src/iv_event.c:93
No locals.
#20 0x00007ffff7b8a768 in iv_fd_epoll_timerfd_poll (st=0x7ffff0024eb0, active=0x7ffff5667bc0, abs=0x63aaf8)
    at ../../../../lib/ivykis/src/iv_fd_epoll.c:484
        run_timers = 1
        batch = {{events = 1, data = {ptr = 0x7ffff0024eb0, fd = -268284240, u32 = 4026683056, u64 = 140737220071088}}}
        ret = 1
        run_events = 1
        i = 1
#21 0x00007ffff7b86865 in iv_fd_poll_and_run (st=0x7ffff0024eb0, abs=0x63aaf8) at ../../../../lib/ivykis/src/iv_fd.c:206
        active = {next = 0x7ffff5667bc0, prev = 0x7ffff5667bc0}
        run_timers = 14
#22 0x00007ffff7b87cb4 in iv_main () at ../../../../lib/ivykis/src/iv_main_posix.c:112
        _abs = {tv_sec = 0, tv_nsec = 0}
        abs = 0x63aaf8
        st = 0x7ffff0024eb0
        run_timers = 1
#23 0x00007ffff7b8568f in iv_work_thread (_thr=0x63aab0) at ../../../../lib/ivykis/src/iv_work.c:185
        thr = 0x63aab0
        pool = 0x636550
#24 0x00007ffff7b88f2b in iv_thread_handler (_thr=0x63ab40) at ../../../../lib/ivykis/src/iv_thread_posix.c:112
        thr = 0x63ab40
#25 0x00007ffff75bb6ba in start_thread (arg=0x7ffff566a700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ffff566a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737310533376, 7160520593864790953, 0, 140737488345423, 8388608, 6546288, 
                -7160532890329148503, -7160537325228518487}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
---Type <return> to continue, or q <return> to quit---
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#26 0x00007ffff72f141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by alltilla** [comment]
Fixed with #2269
