### ISSUE TITLE
dbld/rules image-centos-7 fails in install_pip_packages part

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#3223]
When trying to create a CentOS 7 image locally it fails with the following error message:

```
Step 11/18 : RUN /helpers/dependencies.sh install_pip_packages
 ---> Running in 1006df5353de
+ install_pip_packages
+ case "${OS_PLATFORM}" in
+ python -m pip install --upgrade pip==9.0.3
Collecting pip==9.0.3
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 307, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 842, in _download_http_url
    stream=True,
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 508, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 496, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 606, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c /helpers/dependencies.sh install_pip_packages' returned a non-zero code: 2
make: *** [dbld/rules:146: image-centos-7] Error 2
```
It still worked yesterday, but today fails reproducible.

**Comment by bazsi** [comment]
SSL certificate validation fails for some reason. maybe pypi.org changed a certificate?

**Comment by gaborznagy** [comment]
For me it worked fine, but I see differences that I yet to understand (I had pip version 9.0.3, but before the 8.1.2 uninstalled).
I had no 

See output:
```
OSE$ dbld/rules image-centos-7
cd /home/gabornagy/work/syslog-ng-OSE/dbld/images/ && docker build --build-arg=OS_PLATFORM=centos-7 --build-arg=COMMIT=$(git rev-parse --short HEAD) --network=host -t bala
bit/syslog-ng-centos-7 -f centos-7.dockerfile .
Sending build context to Docker daemon    129kB
Step 1/18 : FROM centos:7
 ---> e934aafc2206
Step 2/18 : LABEL maintainer="Andras Mitzki <andras.mitzki@balabit.com>, Laszlo Szemere <laszlo.szemere@balabit.com>, Balazs Scheidler <balazs.scheidler@oneidentity.com>"
 ---> Running in 27bb51f91e81
Removing intermediate container 27bb51f91e81
 ---> 39ec107eb8b0
Step 3/18 : ARG OS_PLATFORM
 ---> Running in 192647ae81de
Removing intermediate container 192647ae81de
 ---> 1321e84596a9
Step 4/18 : ARG COMMIT
 ---> Running in dbd82b6103af
Removing intermediate container dbd82b6103af
 ---> 4be7562bc66f
Step 5/18 : ENV OS_PLATFORM ${OS_PLATFORM}
 ---> Running in 7b3dd7266572
Removing intermediate container 7b3dd7266572
 ---> 6b0bd40c8baa
Step 6/18 : LABEL COMMIT=${COMMIT}
 ---> Running in ee439e33940b
Removing intermediate container ee439e33940b
 ---> 4af40dc70df2
Step 7/18 : COPY helpers/* /helpers/
 ---> f409556e3be7
Step 8/18 : RUN /helpers/dependencies.sh add_epel_repo
 ---> Running in 8b0089560fb1

.....



Step 11/18 : RUN /helpers/dependencies.sh install_pip_packages
 ---> Running in 83e700f9c816
+ install_pip_packages
+ case "${OS_PLATFORM}" in
+ python -m pip install --upgrade pip==9.0.3
Collecting pip==9.0.3
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.3
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ filter_packages_by_platform /helpers/pip_packages.manifest
+ FILENAME=/helpers/pip_packages.manifest
+ xargs pip install --ignore-installed -U
++ cut -d- -f1
++ echo centos-7
+ OS_GROUP=centos
+ grep -v '#' /helpers/pip_packages.manifest
+ grep -e centos-7 -e 'centos[^-]'
+ cut '-d[' -f1
Collecting nose
  Downloading https://files.pythonhosted.org/packages/99/4f/13fb671119e65c4dce97c60e67d3fd9e6f7f809f2b307e2611f4701205cb/nose-1.3.7-py2-none-any.whl (154kB)
Collecting ply
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
Collecting pathlib2
  Downloading https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
Collecting psutil
  Downloading https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz (449kB)
Collecting pytest
  Downloading https://files.pythonhosted.org/packages/e3/05/26e00e583640d02c6b38ac53a92d8c9fecacde0842c4f2d7c02bbbd0d57f/pytest-4.6.9-py2.py3-none-any.whl (231kB)
Collecting six (from pathlib2)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2)
  Downloading https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest)
  Downloading https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl
Collecting funcsigs>=1.0; python_version < "3.0" (from pytest)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting wcwidth (from pytest)
  Downloading https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest)
  Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest)
  Downloading https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest)
  Downloading https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl (83kB)
Collecting attrs>=17.4.0 (from pytest)
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting packaging (from pytest)
  Downloading https://files.pythonhosted.org/packages/62/0a/34641d2bf5c917c96db0ded85ae4da25b6cd922d6b794648d4e7e07c88e5/packaging-20.3-py2.py3-none-any.whl
Collecting more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" (from pytest)
  Downloading https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f108508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl (52kB)
Collecting configparser>=3.5; python_version < "3" (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
  Downloading https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
  Downloading https://files.pythonhosted.org/packages/96/0a/67556e9b7782df7118c1f49bdc494da5e5e429c93aa77965f33e81287c8c/zipp-1.2.0-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3" (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
  Downloading https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->pytest)
  Downloading https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl (67kB)
Installing collected packages: nose, ply, six, scandir, pathlib2, psutil, configparser, contextlib2, zipp, importlib-metadata, funcsigs, wcwidth, atomicwrites, pluggy, py,
 attrs, pyparsing, packaging, more-itertools, pytest
  Running setup.py install for scandir: started
    Running setup.py install for scandir: finished with status 'done'
  Running setup.py install for psutil: started
    Running setup.py install for psutil: finished with status 'done'
Successfully installed atomicwrites-1.3.0 attrs-19.3.0 configparser-4.0.2 contextlib2-0.6.0.post1 funcsigs-1.0.2 importlib-metadata-1.6.0 more-itertools-5.0.0 nose-1.3.7 p
ackaging-20.3 pathlib2-2.3.5 pluggy-0.13.1 ply-3.11 psutil-5.7.0 py-1.8.1 pyparsing-2.4.6 pytest-4.6.9 scandir-1.10.0 six-1.14.0 wcwidth-0.1.9 zipp-1.2.0
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 83e700f9c816
 ---> bf7f0e64132d
Step 12/18 : RUN /helpers/dependencies.sh install_criterion
 ---> Running in 940bf4ca6b52


```

**Comment by MrAnno** [comment]
`dbld/rules image-centos-7` works for me too.

Did you remove old images? Do you use any corporate VPN?

**Comment by czanik** [comment]
Sorry for the noise. I rarely use corporate VPN, so I was not aware, that it changed system time to something complete nonsense...
