### ISSUE TITLE
syslog-ng blocks on read __nbytes=65536

### ISSUE THREAD

**Issue by pva** [syslog-ng/syslog-ng#4376]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.37.1)
Config version: 3.35
Installer-Version: 3.37.1
Revision: 
Compile-Date: Nov 15 2022 10:15:27
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: graphite,cryptofuncs,csvparser,syslogformat,azure-auth-header,tags-parser,system-source,basicfuncs,timestamp,cef,hook-commands,disk-buffer,stardate,mod-python,pseudofile,secure-logging,afuser,dbparser,add-contextual-data,kvformat,regexp-parser,affile,map-value-pairs,xml,linux-kmsg-format,http,rate-limit-filter,examples,appmodel,tfgetent,confgen,json-plugin,afsocket,afstomp,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

## Platform
Gentoo Linux

## Debug bundle 
(unable to attach, I'll try again after I submit issue)

# Issue
## Failure

We've noticed, that for some reason logging stops and lot's of cron processes hang in ps aux output:
```
ps aux | grep CROND
... lot's of processes
root      747192  0.0  0.0   3360   324 ?        S    мар19   0:00 /usr/sbin/CROND
root      747193  0.0  0.0   3360   324 ?        S    мар19   0:00 /usr/sbin/CROND
root      758395  0.0  0.0   3360   324 ?        S    мар19   0:00 /usr/sbin/CROND
root      758396  0.0  0.0   3360   324 ?        S    мар19   0:00 /usr/sbin/CROND
... lot's of processes
```
Also, it becomes impossible to ssh on the system: ssh login hangs. I've noticed that ssh hangs on attempts to write into syslog. So, I've tried to restart syslog-ng (I had to kill it with -9) and the problem went away. 

So, I started to suspect that this is syslog-ng that hangs. So, once problem returned I've attached with gdb to syslog-ng that is the trace I found:
```
Attaching to process 119875
[New LWP 143388]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fa254156f96 in epoll_wait () from /lib64/libc.so.6
(gdb) thread apply all bt

Thread 2 (Thread 0x7fa252a9c640 (LWP 143388) "syslog-ng"):
#0  0x00007fa25414705c in read () from /lib64/libc.so.6
#1  0x00007fa253ad6439 in read (__nbytes=65536, __buf=0x7fa244004090, __fd=<optimized out>) at /usr/include/bits/unistd.h:47
#2  log_transport_prockmsg_read_method (s=0x556670073520, buf=0x7fa244004090, buflen=65536, aux=<optimized out>) at modules/affile/transport-prockmsg.c:48
#3  0x00007fa2543e190e in log_transport_read (aux=<optimized out>, count=<optimized out>, buf=<optimized out>, self=<optimized out>) at ./lib/transport/logtransport.h:59
#4  log_proto_buffered_server_read_data_method (self=<optimized out>, buf=<optimized out>, len=<optimized out>, aux=<optimized out>) at lib/logproto/logproto-buffered-server.c:593
#5  0x00007fa2543e2df9 in log_proto_buffered_server_read_data (count=65536, buffer=0x7fa244004090, self=0x556670073560) at lib/logproto/logproto-buffered-server.c:648
#6  log_proto_buffered_server_fetch_into_buffer (self=self@entry=0x556670073560) at lib/logproto/logproto-buffered-server.c:683
#7  0x00007fa2543e30ab in log_proto_buffered_server_fetch (s=0x556670073560, msg=0x7fa252a99320, msg_len=0x7fa252a99328, may_read=0x7fa252a9931c, aux=0x7fa252a99330, bookmark=0x556670074098) at lib/logproto/logproto-buffered-server.c:876
#8  0x00007fa2543be009 in log_proto_server_fetch (bookmark=<optimized out>, aux=0x7fa252a99330, may_read=0x7fa252a9931c, msg_len=0x7fa252a99328, msg=0x7fa252a99320, s=<optimized out>) at ./lib/logproto/logproto-server.h:148
#9  log_reader_fetch_log (self=self@entry=0x556670073c70) at lib/logreader.c:512
#10 0x00007fa2543be2e9 in log_reader_work_perform (s=0x556670073c70, cond=<optimized out>) at lib/logreader.c:361
#11 0x00007fa2543c6e41 in _work (self=<optimized out>) at lib/mainloop-io-worker.c:69
#12 0x00007fa253fc49ca in iv_work_thread_got_event () from /usr/lib64/libivykis.so.0
#13 0x00007fa253fc30d3 in __iv_event_run_pending_events () from /usr/lib64/libivykis.so.0
#14 0x00007fa253fc99c5 in iv_fd_epoll_timerfd_poll () from /usr/lib64/libivykis.so.0
#15 0x00007fa253fc55d9 in iv_fd_poll_and_run () from /usr/lib64/libivykis.so.0
#16 0x00007fa253fc6c6a in iv_main () from /usr/lib64/libivykis.so.0
#17 0x00007fa253fc4793 in iv_work_thread () from /usr/lib64/libivykis.so.0
#18 0x00007fa253fc7f95 in iv_thread_handler () from /usr/lib64/libivykis.so.0
#19 0x00007fa2540d5887 in start_thread () from /lib64/libc.so.6
#20 0x00007fa25415793c in clone3 () from /lib64/libc.so.6

Thread 1 (Thread 0x7fa253c5da00 (LWP 119875) "syslog-ng"):
#0  0x00007fa254156f96 in epoll_wait () from /lib64/libc.so.6
#1  0x00007fa253fc97ae in iv_fd_epoll_timerfd_poll () from /usr/lib64/libivykis.so.0
#2  0x00007fa253fc55d9 in iv_fd_poll_and_run () from /usr/lib64/libivykis.so.0
#3  0x00007fa253fc6c6a in iv_main () from /usr/lib64/libivykis.so.0
#4  0x00007fa2543c5ed9 in main_loop_run (self=0x7fa2544583c0 <main_loop>) at lib/mainloop.c:668
#5  0x000055666f9c24db in main (argc=<optimized out>, argv=<optimized out>) at syslog-ng/main.c:311
(gdb) c
Continuing.
[New Thread 0x7fa25229b640 (LWP 166106)]
[New Thread 0x7fa251a9a640 (LWP 166107)]
[Thread 0x7fa251a9a640 (LWP 166107) exited]
...
```

As you see it hangs on read of __nbytes=65536. Do you see a problem here or do we need to debug anything deeper?

Interestingly that after I pressed c (continue) in gdb shell problem immediately went away!

Just for the sake of completeness I wanted to see where CRON proccesses hang, and here they are:
```
 /proc/960580 # cat stack 
[<0>] unix_wait_for_peer+0xb3/0xc0
[<0>] unix_dgram_sendmsg+0x978/0x9f0
[<0>] sock_sendmsg+0x62/0x70
[<0>] __sys_sendto+0xf0/0x160
[<0>] __x64_sys_sendto+0x20/0x30
[<0>] do_syscall_64+0x3b/0xc0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xcb

And same process in debugger:
(gdb) thread apply all bt

Thread 1 (Thread 0x7f9aec5cf740 (LWP 165484) "crond"):
#0  0x00007f9aec6cb01e in read () from /lib64/libc.so.6
#1  0x00007f9aec6528cc in _IO_file_underflow () from /lib64/libc.so.6
#2  0x00007f9aec653902 in _IO_default_uflow () from /lib64/libc.so.6
#3  0x000055c9b56f83e2 in child_process ()
#4  0x000055c9b56f9224 in do_command ()
#5  0x000055c9b56f9571 in job_runqueue ()
#6  0x000055c9b56f5ddd in main ()
(gdb) Quit

```

## Steps to reproduce
I have no clear steps to reproduce this problem, but it happens few times per month on our servers.

## Configuration

```
@version: 3.35
# Syslog-ng default configuration file for Gentoo Linux

# https://bugs.gentoo.org/426814
@include "scl.conf"

options {
	threaded(yes);
	chain_hostnames(no);
	stats_freq(43200);
	mark_freq(3600);
};

source src { system(); internal(); };
destination messages { file("/var/log/messages"); };
log { source(src); destination(console_all); };
```

So do you think this information is enough to dig into problem, or should we try something else?

**Comment by pva** [comment]
[syslog.debun.b612-mon1-grafana.2023-03-20_13-17.287839.tar.gz](https://github.com/syslog-ng/syslog-ng/files/11019073/syslog.debun.b612-mon1-grafana.2023-03-20_13-17.287839.tar.gz)


Attaching debun information. BTW, it's a good idea to change in file name extension from  .tgz to .tar.gz as github did not allow to attach .tgz file here. I've managed to attach only after I change .gz to .tar.gz.

**Comment by pva** [comment]
Is there anything else we could add to help to fix this issue?

**Comment by bazsi** [comment]
Sorry, I remember answering to you. But maybe it's sitting in my drafts folder.

So this seems to block on /proc/kmsg which can only happen if there are multiple readers of /proc/kmsg

Is there any other service or another syslog-ng instance that may open that file in parallel to syslog-ng?

Unfortunately the kernel's interface of that file is not really friendly to nonblocking I/O.

Also, it's been a while I saw this issue, but I vaguely remember using /dev/kmsg as an alternative which works properly from this regard.

Anyway, please check if any other process reads /proc/kmsg first, that could explain why this happens.

**Comment by bazsi** [comment]
Btw, we at Axoflow opened a new discord server for more interactive chats, you can join that at this link:

https://discord.gg/E65kP9aZGm

**Comment by bazsi** [comment]
Closing because of inactivity.
