### ISSUE TITLE
Segmentation Fault on heavy loaded system

### ISSUE THREAD

**Issue by amdrsantos** [syslog-ng/syslog-ng#4500]
# syslog-ng
## Version of syslog-ng
```
syslog-ng 4 (4.1.0)
Config version: 4.0
Installer-Version: 4.1.0
Revision: 4.1.0-1
Compile-Date: Feb 28 2023 15:33:51
Module-Directory: /usr/lib/syslog-ng/4.1
Module-Path: /usr/lib/syslog-ng/4.1
Include-Path: /usr/share/syslog-ng/include
Available-Modules: affile,afmongodb,afprog,afsocket,afsql,afuser,appmodel,basicfuncs,cef,confgen,correlation,cryptofuncs,csvparser,disk-buffer,hook-commands,json-plugin,kvformat,linux-kmsg-format,metrics-probe,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,syslogformat,system-source,tags-parser,timestamp
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```
Service file
```
[Unit]
Description=System Logger Daemon
Documentation=man:syslog-ng(8)
After=network.target

[Service]
Type=notify
ExecStart=/usr/sbin/syslog-ng -F $SYSLOGNG_OPTS --caps "cap_net_bind_service,cap_net_broadcast,cap_net_raw,cap_dac_read_search,cap_chown,cap_fowner=p cap_dac_override,cap_syslog=ep"
ExecReload=/bin/kill -HUP $MAINPID
EnvironmentFile=-/etc/default/syslog-ng
EnvironmentFile=-/etc/sysconfig/syslog-ng
StandardOutput=journal
StandardError=journal
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

## Platform
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## Debug bundle
Not available

# Issue
## Failure
```
root@machine:/home/shared# gdb --args /usr/sbin/syslog-ng --caps "cap_net_bind_service,cap_net_broadcast,cap_net_raw,cap_dac_read_search,cap_chown,cap_fowner=p cap_dac_override,cap_syslog=ep"
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/syslog-ng...(no debugging symbols found)...done.
(gdb) core core.syslog-ng.0.1bc32db9f6824bce90697111c8169742.935.1685438657000000
[New LWP 7934]
[New LWP 935]
[New LWP 7038]
[New LWP 19026]
[New LWP 1080]
[New LWP 13505]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/syslog-ng -F --caps cap_net_bind_service,cap_net_broadcast,cap_net_ra'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000ffffaa36fe98 in strcpy () from /lib/aarch64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0xffff93022e70 (LWP 7934))]
(gdb) bt
#0  0x0000ffffaa36fe98 in strcpy () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000ffffa9d401a8 in ?? () from /usr/lib/syslog-ng/4.1/libsdjournal.so
#2  0x0000ffffaa818460 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#3  0x0000ffffaa840124 in log_msg_drop () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#4  0x0000ffffaa7f6aa0 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#5  0x0000ffffaa7eee90 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#6  0x0000ffffaa7ef644 in log_src_driver_queue_method () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#7  0x0000ffffaa7fb530 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#8  0x0000ffffaa7fba88 in log_source_post () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#9  0x0000ffffa9d40a04 in ?? () from /usr/lib/syslog-ng/4.1/libsdjournal.so
#10 0x0000ffffa9d40b54 in ?? () from /usr/lib/syslog-ng/4.1/libsdjournal.so
#11 0x0000ffffaa801c3c in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
#12 0x0000ffffaa49c72c in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
#13 0x0000ffff93022498 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) thread apply all bt full

Thread 6 (Thread 0xffffa37fbe70 (LWP 13505)):
#0  0x0000ffffaa3c4ae0 in epoll_pwait () from /lib/aarch64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000ffffaa4a14d8 in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
No symbol table info available.
#2  0x0000ffff981b04e0 in ?? ()
No symbol table info available.
#3  0x742064656b63696b in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0xffffa3ffce70 (LWP 1080)):
#0  0x0000ffffaa3c4ae0 in epoll_pwait () from /lib/aarch64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000ffffaa4a14d8 in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
No symbol table info available.
#2  0x0000ffff9c000c70 in ?? ()
No symbol table info available.
#3  0x742064656b63696b in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0xffffa903ee70 (LWP 19026)):
#0  0x0000ffffaa3c4ae0 in epoll_pwait () from /lib/aarch64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000ffffaa4a139c in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
No symbol table info available.
#2  0x0000ffffa4002b50 in ?? ()
No symbol table info available.
#3  0x742064656b63696b in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0xffffa883de70 (LWP 7038)):
#0  0x0000ffffaa3c4ae0 in epoll_pwait () from /lib/aarch64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000ffffaa4a14d8 in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
No symbol table info available.
#2  0x0000ffff94002b50 in ?? ()
No symbol table info available.
#3  0x742064656b63696b in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xffffa9d9c010 (LWP 935)):
#0  0x0000ffffaa3c4ae0 in epoll_pwait () from /lib/aarch64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000ffffaa4a139c in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
No symbol table info available.
#2  0x0000aaab0729ec10 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 0xffff93022e70 (LWP 7934)):
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x0000ffffaa36fe98 in strcpy () from /lib/aarch64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000ffffa9d401a8 in ?? () from /usr/lib/syslog-ng/4.1/libsdjournal.so
No symbol table info available.
#2  0x0000ffffaa818460 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#3  0x0000ffffaa840124 in log_msg_drop () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#4  0x0000ffffaa7f6aa0 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#5  0x0000ffffaa7eee90 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#6  0x0000ffffaa7ef644 in log_src_driver_queue_method () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#7  0x0000ffffaa7fb530 in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#8  0x0000ffffaa7fba88 in log_source_post () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#9  0x0000ffffa9d40a04 in ?? () from /usr/lib/syslog-ng/4.1/libsdjournal.so
No symbol table info available.
#10 0x0000ffffa9d40b54 in ?? () from /usr/lib/syslog-ng/4.1/libsdjournal.so
No symbol table info available.
#11 0x0000ffffaa801c3c in ?? () from /usr/lib/syslog-ng/libsyslog-ng-4.1.so.0
No symbol table info available.
#12 0x0000ffffaa49c72c in ?? () from /usr/lib/aarch64-linux-gnu/libivykis.so.0
No symbol table info available.
#13 0x0000ffff93022498 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

## Steps to reproduce
System is under pressure and a large number of logs are being generated, such that journald is suppressing messages:
```
<30>1 2023-06-05T12:07:16.025+00:00 machine systemd-journald 670 - - Suppressed 519 messages from dbf.service
<30>1 2023-06-05T12:07:46.026+00:00 machine systemd-journald 670 - - Suppressed 2638 messages from dbf.service
<30>1 2023-06-05T12:08:16.027+00:00 machine systemd-journald 670 - - Suppressed 236 messages from dbf.service
<30>1 2023-06-05T12:08:46.031+00:00 machine systemd-journald 670 - - Suppressed 1413 messages from dbf.service
<30>1 2023-06-05T12:09:16.032+00:00 machine systemd-journald 670 - - Suppressed 966 messages from dbf.service
<30>1 2023-06-05T12:09:46.034+00:00 machine systemd-journald 670 - - Suppressed 4142 messages from dbf.service
<30>1 2023-06-05T12:10:16.036+00:00 machine systemd-journald 670 - - Suppressed 3863 messages from dbf.service
<30>1 2023-06-05T12:10:46.037+00:00 machine systemd-journald 670 - - Suppressed 1773 messages from dbf.service
<30>1 2023-06-05T12:11:16.037+00:00 machine systemd-journald 670 - - Suppressed 2430 messages from dbf.service
<30>1 2023-06-05T12:11:46.040+00:00 machine systemd-journald 670 - - Suppressed 985 messages from dbf.service
```
This means, that at least this particular service, is sending more than 10000 messages in 30s.

## Configuration
[GX-79144.syslog-ng.conf.zip](https://github.com/syslog-ng/syslog-ng/files/11663591/GX-79144.syslog-ng.conf.zip)

## Input and output logs (if possible)
```
<30>1 2023-05-30T09:23:46.565+00:00 machine systemd-journald 673 - - Suppressed 2972 messages from dbf.service
<30>1 2023-05-30T09:24:16.577+00:00 machine systemd-journald 673 - - Suppressed 5089 messages from dbf.service


<30>1 2023-05-30T09:24:17.856+00:00 machine systemd 1 - - Started Process Core Dump (PID 29998/UID 0).
<28>1 2023-05-30T09:24:19.994+00:00 machine systemd 1 - - syslog-ng.service: Main process exited, code=killed, status=11/SEGV
<28>1 2023-05-30T09:24:19.995+00:00 machine systemd 1 - - syslog-ng.service: Failed with result 'signal'.
<30>1 2023-05-30T09:24:20.269+00:00 machine systemd 1 - - syslog-ng.service: Service RestartSec=100ms expired, scheduling restart.
<30>1 2023-05-30T09:24:20.270+00:00 machine systemd 1 - - syslog-ng.service: Scheduled restart job, restart counter is at 1.
<30>1 2023-05-30T09:24:20.270+00:00 machine systemd 1 - - Stopped System Logger Daemon.
<30>1 2023-05-30T09:24:20.277+00:00 machine systemd 1 - - Starting System Logger Daemon...
<30>1 2023-05-30T09:24:20.923+00:00 machine systemd 1 - - systemd-coredump@48-29998-0.service: Succeeded.


<45>1 2023-05-30T09:24:22.865+00:00 machine syslog-ng 30092 - [meta sequenceId="1"] syslog-ng starting up; version='4.1.0'
<46>1 2023-05-30T09:24:22.879+00:00 machine syslog-ng 30092 - [meta sequenceId="2"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00000.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.879+00:00 machine syslog-ng 30092 - [meta sequenceId="3"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00004.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.887+00:00 machine syslog-ng 30092 - [meta sequenceId="4"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00008.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.887+00:00 machine syslog-ng 30092 - [meta sequenceId="5"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00023.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.887+00:00 machine syslog-ng 30092 - [meta sequenceId="6"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00009.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.893+00:00 machine syslog-ng 30092 - [meta sequenceId="7"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00002.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.920+00:00 machine syslog-ng 30092 - [meta sequenceId="8"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00036.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.937+00:00 machine syslog-ng 30092 - [meta sequenceId="9"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00031.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.971+00:00 machine syslog-ng 30092 - [meta sequenceId="10"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00016.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:22.988+00:00 machine syslog-ng 30092 - [meta sequenceId="11"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00032.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:23.024+00:00 machine syslog-ng 30092 - [meta sequenceId="12"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00017.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:23.107+00:00 machine syslog-ng 30092 - [meta sequenceId="13"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00007.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:25.236+00:00 machine syslog-ng 30092 - [meta sequenceId="14"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00022.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:25.534+00:00 machine syslog-ng 30092 - [meta sequenceId="15"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00034.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:28.528+00:00 machine syslog-ng 30092 - [meta sequenceId="16"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00044.rqf', number_of_messages='0'
<46>1 2023-05-30T09:24:42.550+00:00 machine syslog-ng 30092 - [meta sequenceId="17"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00013.rqf', number_of_messages='0'
<46>1 2023-05-30T09:26:00.677+00:00 machine syslog-ng 30092 - [meta sequenceId="44"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00035.rqf', number_of_messages='0'
<46>1 2023-05-30T09:26:01.047+00:00 machine syslog-ng 30092 - [meta sequenceId="45"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00011.rqf', number_of_messages='0'
<46>1 2023-05-30T09:26:28.435+00:00 machine syslog-ng 30092 - [meta sequenceId="46"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00042.rqf', number_of_messages='0'
<46>1 2023-05-30T09:26:28.435+00:00 machine syslog-ng 30092 - [meta sequenceId="47"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00041.rqf', number_of_messages='0'
<46>1 2023-05-30T09:26:28.445+00:00 machine syslog-ng 30092 - [meta sequenceId="48"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00027.rqf', number_of_messages='0'
<46>1 2023-05-30T09:26:28.479+00:00 machine syslog-ng 30092 - [meta sequenceId="56"] Reliable disk-buffer state loaded; filename='/tmp/syslog-ng-00043.rqf', number_of_messages='0'
<30>1 2023-05-30T09:24:22.807+00:00 machine syslog-ng 30092 - - [2023-05-30T17:24:22.807029] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 4.1 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.36'
<30>1 2023-05-30T09:24:22.808+00:00 machine syslog-ng 30092 - - [2023-05-30T17:24:22.807669] WARNING: Your configuration file uses an obsoleted keyword, please update your configuration; keyword='stats_freq', change='Use the stats() block. E.g. stats(freq(1));', location='/etc/syslog-ng/syslog-ng.conf:28:5'
<30>1 2023-05-30T09:24:22.847+00:00 machine syslog-ng 30092 - - [2023-05-30T17:24:22.847866] WARNING: mem-buf-size parameter was ignored as it is not compatible with non-reliable queue. Did you mean mem-buf-length?;
<30>1 2023-05-30T09:24:22.852+00:00 machine syslog-ng 30092 - - [2023-05-30T17:24:22.849899] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
<30>1 2023-05-30T09:24:22.857+00:00 machine syslog-ng 30092 - - [2023-05-30T17:24:22.857063] systemd-journal: Current position does not match the previously restored cursor position, seeking to head; cursor='s=1a6a7f8fbaf143979b5d253f5031bffa;i=33ebd9;b=1bc32db9f6824bce90697111c8169742;m=78f849b85;t=5fce5b70ce4dc;x=ca99b8cc623094f7', rc='0', error='Success (0)'
```

**Comment by MrAnno** [comment]
The crash is coming from one of the following sources, most likely from its ack tracker:

```
system(); # journal
internal();
pipe("/tmp/internal-mgmt-syslog-ng.pipe" flags(syslog-protocol));
```

**Comment by amdrsantos** [comment]
Ok, what is your recommendation?
