### ISSUE TITLE
s3 destination does not start

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#4697]
When I try to start syslog-ng with the s3 destination enabled, I get an error:
```
[2023-11-03T16:37:17.280174] Error loading Python module; module='syslogng.modules.s3', exception='ImportError: cannot import name \'SharedBool\' from \'syslogng.modules.s3.s3_object\' (/usr/lib64/syslog-ng/python/syslogng/modules/s3/s3_object.py)'
[2023-11-03T16:37:17.280238] Seems you are missing a module that may be referenced by a syslog-ng plugin implemented in Python. These modules need to be installed either using your platform's package management tools (e.g. apt/dnf/yum) or Python's own package management tool (e.g. pip). syslog-ng authors recommend using pip and a dedicated Python virtualenv. You can initialize such a virtualenv using the `syslog-ng-update-virtualenv` command. This command will initialize the virtualenv and install all packages needed by plugins shipped with syslog-ng itself from the Python Package Index (PyPI). If you need any additional Python libraries for your local scripts, you can install those using the `pip` command located in the virtualenv's bin directory; module='syslogng.modules.s3.s3_object'
[2023-11-03T16:37:17.280258] python: importing Python module; module='traceback', filename='/usr/lib64/python3.11/traceback.py'
Traceback (most recent call last):
  File "/usr/lib64/syslog-ng/python/syslogng/modules/s3/__init__.py", line 23, in <module>
    from .s3_destination import S3Destination
  File "/usr/lib64/syslog-ng/python/syslogng/modules/s3/s3_destination.py", line 23, in <module>
    from .s3_object import S3Object, S3ObjectPersist, SharedBool, ConstructorError, PersistLoadError, AlreadyFinishedError
ImportError: cannot import name 'SharedBool' from 'syslogng.modules.s3.s3_object' (/usr/lib64/syslog-ng/python/syslogng/modules/s3/s3_object.py)
[2023-11-03T16:37:17.284059] python-dest: Error looking up Python driver class; driver='d_s3#0', class='syslogng.modules.s3.S3Destination', exception='None'
[2023-11-03T16:37:17.284108] Error initializing message pipeline; plugin_name='python', location='/usr/lib64/syslog-ng/python/syslogng/modules/s3/scl/s3.conf:44:5'
[2023-11-03T16:37:17.285591] Running application hooks; hook='4'
```
If I removed ```SharedBool``` from the ```s3_destination.py``` import line, the s3 destination seems to work.

**Comment by bazsi** [comment]
hmm.. this is indeed undefined in s3_object and is unused in s3_destination.

@alltilla ?

**Comment by alltilla** [comment]
I don't know how this has not came up earlier. Maybe a dirty install dir shadowed this problem.
