### ISSUE TITLE
S3 Destination causes errors when system python is < 3.10

### ISSUE THREAD

**Issue by if-jeremy** [syslog-ng/syslog-ng#5131]
# syslog-ng
## Version of syslog-ng
4.8.0

## Platform
Amazon Linux 2023

# Issue
## Failure
When running syslog-ng on Amazon Linux 2023, using the rpm packages from COPR, and enabling the S3 destination, we get the following Python traceback in the debug output:

```
[2024-09-24T16:12:25.374781] Exception while calling a Python function; caller='d_s3#0', class='syslogng.modules.s3.S3Destination', function='open', exception='TypeError: glob() got an unexpected keyword argument \'root_dir\''
[2024-09-24T16:12:25.374781] python: importing Python module; module='traceback', filename='/usr/lib64/python3.9/traceback.py'
Traceback (most recent call last):
  File "/usr/lib64/syslog-ng/python/syslogng/modules/s3/s3_destination.py", line 297, in open
    self.__load_persist()
  File "/usr/lib64/syslog-ng/python/syslogng/modules/s3/s3_destination.py", line 185, in __load_persist
    for path_str in glob(pathname="*.json", root_dir=self.working_dir):
TypeError: glob() got an unexpected keyword argument 'root_dir'
[2024-09-24T16:12:25.374781] Error establishing connection to server; driver='d_s3#0', worker_index='0', location='/usr/lib64/syslog-ng/python/syslogng/modules/s3/scl/s3.conf:47:5'
```

According to my research, the glob() function did not get the root_dir parameter until Python 3.10 (see: https://docs.python.org/3/library/glob.html ), so accordingly, any OS with a system python prior to 3.10 will get this error.  AL2023 does have a python 3.11 package available, but it is not recommended to replace the /usr/bin/python3 symlink from 3.9 to 3.11.

$ gdb syslog-ng
 run
-->

## Steps to reproduce
Install syslog-ng on AL2023 (and presumably any other OS with a system python prior to 3.10)
Enable S3 destination
Run syslog-ng in debug mode to see the error

**Comment by HofiOne** [comment]
thanks for the report, we will investigate it!
